// Extended destinations data
const destinations = [
    {
        id: 1,
        name: "Himalayan Trek",
        type: "mountain",
        price: 899,
        image: "https://images.unsplash.com/photo-1464822759849-deb9df5c95c9?ixlib=rb-4.0.1&auto=format&fit=crop&w=500&q=60",
        description: "Trek through the majestic Himalayas with experienced guides",
        duration: "10 days",
        difficulty: "Advanced",
        rating: 4.9,
        features: ["Expert Guides", "Mountain Lodges", "Altitude Training"]
    },
    {
        id: 2,
        name: "Bali Beach Retreat",
        type: "beach",
        price: 699,
        image: "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?ixlib=rb-4.0.1&auto=format&fit=crop&w=500&q=60",
        description: "Luxury beachfront accommodation with water activities",
        duration: "7 days",
        difficulty: "Easy",
        rating: 4.7,
        features: ["Beachfront Villa", "Spa Treatments", "Water Sports"]
    },
    {
        id: 3,
        name: "Wilderness Camping",
        type: "camping",
        price: 499,
        image: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?ixlib=rb-4.0.1&auto=format&fit=crop&w=500&q=60",
        description: "Authentic camping experience in pristine wilderness",
        duration: "4 days",
        difficulty: "Moderate",
        rating: 4.8,
        features: ["Professional Gear", "Wildlife Watching", "Campfire Cooking"]
    },
    {
        id: 4,
        name: "Japanese Culture Tour",
        type: "cultural",
        price: 1199,
        image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?ixlib=rb-4.0.1&auto=format&fit=crop&w=500&q=60",
        description: "Immerse yourself in traditional Japanese culture and history",
        duration: "8 days",
        difficulty: "Easy",
        rating: 4.9,
        features: ["Temple Stays", "Cultural Workshops", "Local Cuisine"]
    },
    {
        id: 5,
        name: "Alpine Adventure",
        type: "mountain",
        price: 1099,
        image: "https://images.unsplash.com/photo-1464822759849-deb9df5c95c9?ixlib=rb-4.0.1&auto=format&fit=crop&w=500&q=60",
        description: "Swiss Alps hiking with luxury mountain huts",
        duration: "6 days",
        difficulty: "Moderate",
        rating: 4.8,
        features: ["Alpine Huts", "Cable Car Rides", "Mountain Guides"]
    },
    {
        id: 6,
        name: "Caribbean Paradise",
        type: "beach",
        price: 1299,
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.1&auto=format&fit=crop&w=500&q=60",
        description: "Private island experience in the Caribbean",
        duration: "5 days",
        difficulty: "Easy",
        rating: 4.9,
        features: ["Private Beach", "Snorkeling", "Luxury Resort"]
    },
    {
        id: 7,
        name: "Safari Camping",
        type: "camping",
        price: 1499,
        image: "https://images.unsplash.com/photo-1508873696983-2dfd5898f08b?ixlib=rb-4.0.1&auto=format&fit=crop&w=500&q=60",
        description: "African safari with luxury tent camping",
        duration: "7 days",
        difficulty: "Easy",
        rating: 5.0,
        features
